apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: talent-app
type: Opaque
stringData:
  MONGODB_URI: "mongodb+srv://USERNAME:PASSWORD@CLUSTER.mongodb.net/?retryWrites=true&w=majority&appName=satyam"
  PORT: "5000"